name: Blob storage website CI

on:
    push:
        branches:
          - main
        paths:
         - 'cloudresweb/index.html'
         - 'cloudresweb/scripts/**'
         - 'cloudresweb/styles/**'

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
            az storage blob upload-batch --account-name escloudresumewebstorage --auth-mode key -d '$web' -s cloudresweb/. --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v2
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cdn-escloud-1" --name "cdn-escloud-endpoint-1" --resource-group "es_cloud_resume_resources"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
